main/urls.py
from django.urls import path
from .views import *

app_name = 'main'


urlpatterns = [
    path('', index_view, name='index'),
    path('', contact_view, name='contact')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

# About Model
class About(models.Model):
    description = models.TextField()

    class Meta():
        verbose_name = "About me"
        verbose_name_plural = "About me"

    def __str__(self):
        return "About me"
    
# Service Model
class Service(models.Model):
    name = models.CharField(max_length=100, verbose_name="Service name")
    description = models.TextField(verbose_name="About service")

    def __str__(self):
        return self.name
    

# Works Model
class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name="Project title")
    project_badge = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/project_img', default='media/project_img/default.jpg')

    def __str__(self):
        return self.title
    

# Contact Model
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)  


    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name
    

main/forms.py
from django import forms
from main.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "message"]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from django.contrib import messages
from .forms import ContactForm

# Create your views here.
def index_view(request):
    about = About.objects.all()
    services = Service.objects.all()
    projects = Project.objects.all()
    context = {'about':about, 'services':services, 'projects':projects}
    if request.method == "post":
        form = ContactForm(request.post)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'your ticket submited sucessfully')
        else:
            messages.add_message(request, messages.ERROR, 'your ticket did not submited ')

    return render(request, 'include/index.html', context)



# def contact_view(request):
#     return render(request, 'include/contact.html')


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # messages.info(request,'Thanks for contacting us! We will get back to you soon')
            return HttpResponse('done')
        else:
            messages.info(request,'Some error in saving form!')
            return redirect('/')
    else:
        form = ContactForm()
        return render(request,'iclude/index.html', {'form': form})

main/templates/include/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>portfolio</title>
</head>
<body>
    
</body>
</html>

main/templates/include/contact.html
{% load static %}
{% block content %}


<!-- Contact -->
<section id="contact" class="section container">
    <h2 class="section__title">Let's Connect!</h2>
    <div class="contact">

        <!-- Add icon library -->
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Add font awesome icons -->
        <a href="https://github.com/mohrezvelayati" class="fa fa-github"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-instagram"></a>
        <a href="#" class="fa fa-telegram"></a>
        
        <br>

        <!-- <form class="contact__form" method="post" action="{% url 'main:contact' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="contact__field-wrapper">
                <label for="contactNameTxt">Name:</label>
                <input id="contactNameTxt" type="text" placeholder="What's your name?"/>
            </div>
            <div class="contact__field-wrapper">
                <label for="contactMailTxt">Email:</label>
                <input id="contactNameTxt" type="text" placeholder="What's your e-mail?"/>
            </div>
            <div class="contact__field-wrapper">
                <label for="contactDescriptionTxt">Message:</label>
                <textarea id="contactDescriptionTxt" placeholder="Lets connect!"></textarea>
            </div>

            <button type="submit" class="contact__submit-btn">Submit</button>
        </form> -->

        <span class="contact__illustration">
            <img src="{% static './assets/illustrations/connect.svg' %}" alt="Group of people connecting with each other"/>
        </span>
    </div>
</section>


{% endblock %}

main/templates/include/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,100&display=swap"
        rel="stylesheet">

    <!-- JavaScript Libraries -->
    <script src="https://unpkg.com/sweet-scroll/sweet-scroll.min.js"></script>

    <!-- CSS & JS -->
    <link rel="stylesheet" href="{% static './style.css' %}" />
    <script src="{% static './index.js' %}" defer></script>

    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="100% FREE Professional Portfolio Templates - Plain Template" />
    <meta name="keywords" content="OSSPH, Free portfolio" />
    <title> Hax | a Freefolio template by OSSPH</title>

    <!-- Icons -->
    <link rel="icon" href="{% static './favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static './assets/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static './assets/icons/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static './assets/icons/apple-touch-icon-180x180.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static './assets/icons/apple-touch-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static './assets/icons/apple-touch-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static './assets/icons/apple-touch-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static './assets/icons/apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static './assets/icons/apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static './assets/icons/apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static './assets/icons/apple-touch-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static './assets/icons/apple-touch-icon-57x57.png' %}">
</head>

<body>
    <main>
        <!-- Hero Header -->
        <header id="heroHeader" class="hero-header">
            <nav id="navBar" class="nav">
                <div class="container">
                    <button type="button" id="hamburgerBtn" class="nav__hamburger-btn">
                        <span class="nav__hamburger-top"></span>
                        <span class="nav__hamburger-center"></span>
                        <span class="nav__hamburger-bottom"></span>
                    </button>
                    <ul id="navList" class="nav__list">
                        <li class="nav__list-item">
                            <a class="nav__list-link active" href="#heroHeader">&lt;Home &sol;&gt;</a>
                        </li>
                        <li class="nav__list-item">
                            <a class="nav__list-link" href="#services">&lt;Services &sol;&gt;</a>
                        </li>
                        <li class="nav__list-item">
                            <a class="nav__list-link" href="#works">&lt;Works &sol;&gt;</a>
                        </li>
                        <li class="nav__list-item">
                            <a class="nav__list-link" href="#contact">&lt;Contact &sol;&gt;</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <section class="header__container container">
                <div class="header__left">
                    <span class="header__sup-text">Hello There! I am a</span>
                    <h1 class="header__title">
                        <span class="header__title-1" data-role="WEB">Web</span>
                        <span class="header__title-2" data-role="DEVELOPER">Developer</span>
                    </h1>
                    {% for text in about %}
                    <p class="header__msg">{{text.description}}</p>
                    {% endfor %}
                    <a href="#" class="header__resume">Resume</a>
                </div>
                <div class="header__right">
                    <img src="{% static './assets/illustrations/header.svg' %}" alt="Header section illustration" />
                </div>
            </section>
            <span class="header__bg"></span>
        </header>

        <!-- Services -->
        <section id="services" class="section container">
            <h2 class="section__title">Services</h2>
            <div class="service-cards">
                {% for service in services %}
                <article class="service-card__box">
                    <span class="service-card__illustration">
                        <img src="{% static './assets/services/support.svg' %}" alt="Support Illustration" />
                    </span>


                    <h3 class="service-card__title">{{service.name}}</h3>
                    <p class="service-card__msg">{{service.description}}</p>

                    <span class="service-card__bg"></span>
                </article>
                {% endfor %}
                <!-- <article class="service-card__box">
                <span class="service-card__illustration">
                    <img src="{% static './assets/services/design.svg' %}" alt="Design Illustration"/>
                </span>
                <h3 class="service-card__title">Design</h3>
                <p class="service-card__msg">Specialized in creating stunning websites that are both visually appealing and user-friendly.</p>
                <span class="service-card__bg"></span>
            </article>
            <article class="service-card__box">
                <span class="service-card__illustration">
                    <img src="{% static './assets/services/developing.svg' %}" alt="Deploy Illustration"/>
                </span>
                <h3 class="service-card__title">Developing</h3>
                <p class="service-card__msg"> I offer custom web development services tailored to your specific needs as a solo professional.</p>
                <span class="service-card__bg"></span>
            </article> -->
            </div>
        </section>

        <!-- Sample Works -->
        <section id="works" class="section container">
            <h2 class="section__title">My Works</h2>
            <div class="works">
                {% for project in projects %}
                <article class="work">
                    <div class="work__box">
                        <span class="work__img-box">
                            {% if project.image %}
                            <img src="{{project.image}}" alt="My Work 1" />
                            {% endif %}
                        </span>
                        <h3 class="work__title">{{project.title}}</h3>
                        <span class="work__badges">
                            <span class="work__badge">{{project.project_badge}}</span>
                            <!-- <span class="work__badge">{{project.project_badge}}</span>
                    <span class="work__badge">{{project.project_badge}}</span> -->
                        </span>
                    </div>
                </article>
                {% endfor %}
                <!-- <article class="work">
                <div class="work__box">
                    <span class="work__img-box">
                    <img src="{{project.image.url}}" alt="My Work 1"/>
                </span>
                    <h3 class="work__title">My Landing Page</h3>
                    <span class="work__badges">
                    <span class="work__badge">HTML</span>
                    <span class="work__badge">CSS</span>
                    <span class="work__badge">JavaScript</span>
                </span>
                </div>
            </article>
            <article class="work">
                <div class="work__box">
                    <span class="work__img-box">
                    <img src="{% static '' %}" alt="My Work 1"/>
                </span>
                    <h3 class="work__title">My Landing Page</h3>
                    <span class="work__badges">
                    <span class="work__badge">HTML</span>
                    <span class="work__badge">CSS</span>
                    <span class="work__badge">JavaScript</span>
                </span>
                </div>
            </article>
            <article class="work">
                <div class="work__box">
                    <span class="work__img-box">
                    <img src="{% static './assets/works/sample.png' %}" alt="My Work 1"/>
                </span>
                    <h3 class="work__title">My Landing Page</h3>
                    <span class="work__badges">
                    <span class="work__badge">HTML</span>
                    <span class="work__badge">CSS</span>
                    <span class="work__badge">JavaScript</span>
                </span>
                </div>
            </article>
            <article class="work">
                <div class="work__box">
                    <span class="work__img-box">
                    <img src="{% static './assets/works/sample.png' %}" alt="My Work 1"/>
                </span>
                    <h3 class="work__title">My Landing Page</h3>
                    <span class="work__badges">
                    <span class="work__badge">HTML</span>
                    <span class="work__badge">CSS</span>
                    <span class="work__badge">JavaScript</span>
                </span>
                </div>
            </article>
            <article class="work">
                <div class="work__box">
                    <span class="work__img-box">
                    <img src="{% static './assets/works/sample.png' %}" alt="My Work 1"/>
                </span>
                    <h3 class="work__title">My Landing Page</h3>
                    <span class="work__badges">
                    <span class="work__badge">HTML</span>
                    <span class="work__badge">CSS</span>
                    <span class="work__badge">JavaScript</span>
                </span>
                </div>
            </article> -->
            </div>
        </section>

        <!-- Contact -->
        
        <!-- {% include 'include/contact.html' %} -->
        <!-- <section id="contact" class="section container">
        <h2 class="section__title">Let's Connect!</h2>
        <div class="contact">
            
            <form class="contact__form" method="post" action="{% url 'main:contact' %}">
                {% csrf_token %}
                
                <div class="contact__field-wrapper">
                    <label for="contactNameTxt">Name:</label>
                    <input name="name" id="contactNameTxt" type="text" placeholder="What's your name?"/>
                </div>
                <div class="contact__field-wrapper">
                    <label for="contactMailTxt">Email:</label>
                    <input name="email" id="contactNameTxt" type="text" placeholder="What's your e-mail?"/>
                </div>
                <div class="contact__field-wrapper">
                    <label for="contactDescriptionTxt">Message:</label>
                    <textarea name="message" id="contactDescriptionTxt" placeholder="Lets connect!"></textarea>
                </div>

                <button type="submit" class="contact__submit-btn">Submit</button>
            </form>

            <span class="contact__illustration">
                <img src="{% static './assets/illustrations/connect.svg' %}" alt="Group of people connecting with each other"/>
            </span>
        </div>
    </section> -->

        <!-- Footer -->
        <footer class="footer">
            <a href="https://github.com/mohrezvelayati" target="_blank"
                class="footer__link">MohammadReza Velayati</a>
        </footer>
    </main>
</body>

</html>

main/templates/include/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {{about.descriptions}}
    {% for about in abouts %}
    <p>{{about}}</p>
    {% endfor %}
</body>

</html>